### ISSUE TITLE
TintColor throws a warning (iOS)

### ISSUE THREAD

**Issue by MarkEstefanos** [expo/react-native-fade-in-image#6]
Using tintColor throws an error but the tintColor is still used in the image (on iOS) :

```
<FadeIn placeholderStyle={{ backgroundColor: '#E8E8EE' }}>
              <Image style = {styles.chevron}
              resizeMode = {'contain'}
              source = {require('../assets/icons/chevron.png')}/>
 </FadeIn>

const styles = StyleSheet.create({
chevron: {
    width: 20,
    tintColor: '#ACAFB5',
    marginRight: 8,
    height: 72,
  }
})
```

<img width="466" alt="screen shot 2017-03-12 at 9 44 53 pm" src="https://cloud.githubusercontent.com/assets/7613936/23841822/4088764a-076d-11e7-872c-d1f851a1434d.png">

Solution seems to be to remove Image-only styles when passing the style to the parent View. I'll try to PR in the next few days when I get a chance.

**Comment by sonaye** [comment]
```diff
<FadeIn placeholderStyle={{ backgroundColor: '#e8e8ee' }}>
  <Image
    style={styles.chevronModified}
    resizeMode="contain"
    source={require('../assets/icons/chevron.png')}
  />
</FadeIn>

const styles = StyleSheet.create({
  chevron: {
    width: 20,
    tintColor: '#acafb5',
    marginRight: 8,
    height: 72
  },
  chevronModified: {
    width: 20,
-   tintColor: '#acafb5',
    marginRight: 8,
    height: 72
  }
});
```

Submitting a whole PR for this is unnecessary.

**Comment by MarkEstefanos** [comment]
Wouldn't that just remove the tint from my image? Sorry if I'm missing something obvious.
